"""Updated Track model

Revision ID: 2fcfe8d79534
Revises: 98ebc0cc3fa1
Create Date: 2023-04-17 19:13:27.269161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcfe8d79534'
down_revision = '98ebc0cc3fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_track_id', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('track_uri', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('album_uri', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('artist_uri', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('album_cover_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('album_cover_url')
        batch_op.drop_column('artist_uri')
        batch_op.drop_column('album_uri')
        batch_op.drop_column('track_uri')
        batch_op.drop_column('spotify_track_id')

    # ### end Alembic commands ###
